import { Outfit } from "next/font/google"; // Modern font
import "./globals.css";
import { ThemeProvider } from "@/app/components/ThemeProvider";

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={outfit.variable}>
      <body className="bg-white text-black dark:bg-gray-900 dark:text-white antialiased overflow-x-hidden">
        <div className="fixed inset-0 z-0 pointer-events-none">
          <div className="stars"></div>
          <div className="stars2"></div>
          <div className="stars3"></div>
        </div>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}

